server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
 
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
security:
   oauth2:
    resource:
      userInfoUri: http://localhost:9999/user