INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (1, 'USA', 'PEN', 3.87);
INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (2, 'PEN', 'USA', 0.26);
INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (3, 'EUR', 'PEN', 4.42);
INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (4, 'PEN', 'EUR', 0.23);
INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (5, 'JPY', 'PEN', 29.36);
INSERT INTO TIPO_CAMBIO (ID, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO) VALUES (6, 'PEN', 'JPY', 0.034);