server:
   port: 8099

eureka:
  client:
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: AUTH-SERVER 
    trx:
      path: /transacion/**
      sensitive-headers:
      service-id: TRANSACION

        
        
        
